### ISSUE TITLE
Failure in release plugin and no way to correct data

### ISSUE THREAD

**Issue by antony** [grails-samples/grails-website#14]
I received this failure when I used grails publish-plugin

Notifying plugin portal 'http://grails.org/plugin/feature-switch' of release...| Error Error executing script PublishPlugin: groovyx.net.http.HTTPBuilder (Use --stacktrace to see the full trace)

No idea why, but that is a separate issue. The main issue is that I have just released version 0.3 and only 0.2 is listed in the portal.

**Comment by lhotari** [comment]
Closing old issue.
