### ISSUE TITLE
Font icons not loading

### ISSUE THREAD

**Issue by grantmcconnaughey** [grails-samples/grails-website#57]
Font icons don't seem to be loading properly. I'm getting nothing but blank boxes where the icons on buttons used to be. I'm seeing this on the plugin detail page, in particular. Here are the console errors:

    Font from origin 'https://grails.org' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://grails.org' is therefore not allowed access. elasticsearch:1

    Failed to load resource: the server responded with a status of 404 (Not Found) https://grails.org/static/pOs3lW8rfRE0lB0GLjdnRL7bp57mztmeknw0Ol95WIB.png

    Failed to load resource: the server responded with a status of 404 (Not Found) https://grails.org/static/KyfMMV6MCxdwTELxGrqfAcZ6him1G1bVlwH0biUzgWT.png

    2Font from origin 'https://grails.org' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://grails.org' is therefore not allowed access.

**Comment by lhotari** [comment]
fixed when updating grails.org website some time ago.
