### ISSUE TITLE
can't update plugin's wiki description

### ISSUE THREAD

**Issue by domurtag** [grails-samples/grails-website#58]
When I tried to edit a plugin's wiki description, I was presented with the screen shown in the attached image. It was impossible to press the Update or Cancel buttons, even if I clicked on the part of the screen where they appeared.

I was able to workaround the issue by triggering the click of the Update button in the JavaScript console
````
$('#updatePlugin').click()
````
I tried Firefox and Chrome, but the problem occurs in both
![screen shot 2014-09-02 at 18 10 54](https://cloud.githubusercontent.com/assets/1050770/4122459/a50f63c4-32c4-11e4-859c-6cd312d14548.png)

**Comment by lhotari** [comment]
Fixed already some time ago.
